package com.skylanka.ticketmanagement.exception;

public enum ErrorCode {
    BOOKING_NOT_FOUND,
    PAYMENT_NOT_FOUND,
    TICKET_NOT_FOUND,
    PAYMENT_NOT_COMPLETED,
    BOOKING_CANCELLED,
    TICKET_ALREADY_EXISTS,
    INVALID_STATUS_TRANSITION,
    INVALID_QR_TOKEN,
    TICKET_NOT_ACTIVE,
    UNAUTHORIZED_ACCESS,
    DUPLICATE_TICKET_NUMBER,
    PDF_GENERATION_FAILED,
    QR_GENERATION_FAILED,
    INTERNAL_ERROR
}
